spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ENC(AJaQFPuSrkftD/GqCup8k0sscds2Oepo)
    password: ENC(VXZaPxK04REGAklzLvIdc6ZKPAaeBtV/)
    url: ENC(oKsohGWzGOmHMtYERTzqA0gn3yUXEm9uXcjgyZlmb+Jfap3gZiAkqS+QqcR6aIxA9d2xlRjreJw=)

  jpa:
    hibernate:
      ddl-auto: "update" #'create-drop'
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

msk:
  m: "abcd"


#Spring Boot 3.X
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

